* Updated the following NPM packages:     - vue     - socket.io     - socket.io-client     - cookie-parser     - @types/jasmine     - jasmine     - ts-node     - ts-node-dev * Removed unused package-lock.json files in /common and /server. * Fixed unit test issues. * Installed @types/cookie-parser NPM package. * Overhauled socket and eventBus functionality to add type safety, consolidate socket event handling, and fix issues relating to event subscription/unsubscription (ie those times when the highlight for the event/chat buttons wouldn't update when they should), as well as adding connection resiliency. * Updated readyToQuit() and unreadyToQuit() endpoints in GameController to not broadcast gamePlayerReadyToQuit or gamePlayerNotReadyToQuit events, respectively, if the readyToQuitVisibility setting is set to 'hidden'.  If broadcasting the event, if the readyToQuitVisibility setting is NOT set to visible, the player Id is not included in the response data. * Updated LedgerRow component:     - Added functionality to prevent a player from trying to settle a debt if they have none of the relevant funds (credits/specialist tokens).     - Fixed settleDebt() method not updating the user player's credit/specialist token amounts when settling a debt.     - Updated settleDebt() method to improve toast message so that it reflects whether or not the player was only able to pay off some of the debt. * Renamed main.js to main.ts to add TypeScript support. * Updated store.ts to use constants for some mutation names. * Updated GamePlayerReadyToQuit and GamePlayerNotReadyToQuit mutations in store.ts to account for the playerId not being supplied, and to update the readyToQuitCount. * Renamed sockets.ts to socket.js and updated to be SocketService.     - Updated getUserId() method to fix circumstances where the returned Promise would not get resolved.     - Moved gameRoomjoined and gameRoomLeft socket event handling functionality to PlayerServerSocketEventHandler. * Moved roomExists(), playerRoomExists() and getOnlinePlayers() methods out of BroadcastService and into new SocketService. * Moved LedgerType enum from server to common. * Updated SpecialistIcon component to use TypeScript and to specify the correct type for its specialist prop (fixes "error TS2322: Type 'Specialist | null' is not assignable to type 'Record<string, any> | undefined'" error in CombatActorDescription component).